#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Window Config --------------------------------------------------------------
bspc config border_width         5
bspc config window_gap           0
bspc config top_padding          0
bspc config bottom_padding       0
bspc config right_padding        0
bspc config left_padding         0
# ----------------------------------------------------------------------------

# Visual options -------------------------------------------------------------
bspc config split_ratio          0.50
#bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true
#bspc config pointer_follows_monitor true
#bspc config ignore_ewmh_fullscreen false
#bspc config ignore_ewmh_focus false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config normal_border_color "#F9F9F9"
bspc config active_border_color "#F9F9F9"
bspc config focused_border_color "#F9F9F9"
#bspc config auto_alternate true
#bspc config auto_cancel true
# ----------------------------------------------------------------------------

# Window Rules ---------------------------------------------------------------
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^0'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# ----------------------------------------------------------------------------

# Set wall -------------------------------------------------------------------
~/.fehbg
# ----------------------------------------------------------------------------

# Mpd ------------------------------------------------------------------------
mpd ~/.mpd/config.conf &
# ----------------------------------------------------------------------------

# Compositor -----------------------------------------------------------------
# picom &
# ----------------------------------------------------------------------------

# Notify Dll -----------------------------------------------------------------
nm-applet &
xrdb .Xresources &
xrdb merge .Xresources &
dbus-launch /usr/bin/dunst &
exec tint2 &
xsetroot -cursor_name left_ptr &
# End ------------------------------------------------------------------------
