#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Window Config --------------------------------------------------------------
bspc config border_width         0
bspc config border_radius        0
bspc config window_gap           10
bspc config top_padding          0
bspc config bottom_padding       0
bspc config right_padding        0
bspc config left_padding         0
# ----------------------------------------------------------------------------

# Visual options -------------------------------------------------------------
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false
#bspc config ignore_ewmh_fullscreen false
#bspc config ignore_ewmh_focus false
bspc config remove_unplugged_monitors true
#bspc config normal_border_color "#001D24"
#bspc config active_border_color "#001D24"
#bspc config focused_border_color "#00181E"
#bspc config presel_border_color "#001B22"
#bspc config urgent_border_color "#CB4B16"
#bspc config focused_locked_border_color "#B58900"
#bspc config normal_frame_opacity 0.0
#bspc config focused_frame_opacity 0.0
#bspc config auto_alternate true
#bspc config auto_cancel true
# ----------------------------------------------------------------------------

# Window Rules ---------------------------------------------------------------
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# ----------------------------------------------------------------------------

# Set wall -------------------------------------------------------------------
 feh --bg-scale $HOME/.wallpaper/night.jpg
# ----------------------------------------------------------------------------

# Polybar --------------------------------------------------------------------
bash ~/.config/polybar/launch.sh --forest
# ----------------------------------------------------------------------------

# Mpd ------------------------------------------------------------------------
mpd ~/.mpd/config.conf
# ----------------------------------------------------------------------------

# Compositor -----------------------------------------------------------------
picom
# ----------------------------------------------------------------------------

# Notify Dll -----------------------------------------------------------------
xrdb .Xresources
xrdb merge .Xresources
dbus-launch dunst
# End ------------------------------------------------------------------------
